#!/usr/bin/env npx tsx
/**
 * Theme CSS Generator
 *
 * Generates CSS variable declarations from TypeScript theme files
 * and updates index.css with the active themes.
 *
 * Usage:
 *   npm run theme:generate          # Update index.css with active themes
 *   npm run theme:generate -- --preview   # Preview without updating
 *   npm run theme:generate -- --theme washi mori  # Use specific themes
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
import {
  ACTIVE_LIGHT_THEME,
  ACTIVE_DARK_THEME,
  allThemes,
  themeToCss,
  type ThemeConfig,
} from '../src/themes';

// Parse command line arguments
const args = process.argv.slice(2);
const previewMode = args.includes('--preview');
const themeIndex = args.indexOf('--theme');

let lightTheme: ThemeConfig = ACTIVE_LIGHT_THEME;
let darkTheme: ThemeConfig = ACTIVE_DARK_THEME;

// Check for custom theme arguments
if (themeIndex !== -1) {
  const lightName = args[themeIndex + 1];
  const darkName = args[themeIndex + 2];

  if (lightName && allThemes[lightName]) {
    lightTheme = allThemes[lightName];
  } else if (lightName) {
    console.error(`Unknown light theme: ${lightName}`);
    console.error(`Available themes: ${Object.keys(allThemes).join(', ')}`);
    process.exit(1);
  }

  if (darkName && allThemes[darkName]) {
    darkTheme = allThemes[darkName];
  } else if (darkName) {
    console.error(`Unknown dark theme: ${darkName}`);
    console.error(`Available themes: ${Object.keys(allThemes).join(', ')}`);
    process.exit(1);
  }
}

// Generate the CSS
const lightCss = themeToCss(lightTheme.colors);
const darkCss = themeToCss(darkTheme.colors);

const generatedCss = `/* THEME-START - Generated by npm run theme:generate */
/* Theme: ${lightTheme.displayName} (Light) + ${darkTheme.displayName} (Dark)
   Generated: ${new Date().toISOString().split('T')[0]}
   Available themes: ${Object.keys(allThemes).join(', ')} */

/* Light Theme: ${lightTheme.displayName} - ${lightTheme.description} */
:root {
${lightCss}
}

/* Dark Theme: ${darkTheme.displayName} - ${darkTheme.description} */
[data-theme="dark"] {
${darkCss}
}
/* THEME-END */`;

if (previewMode) {
  console.log('\n=== Preview Mode ===\n');
  console.log(generatedCss);
  console.log('\n=== End Preview ===\n');
  console.log('Run without --preview to update index.css');
  process.exit(0);
}

// Read current index.css
const indexCssPath = path.join(__dirname, '../src/index.css');
let indexCss = fs.readFileSync(indexCssPath, 'utf-8');

// Try to find existing THEME-START/THEME-END markers
const markerRegex = /\/\* THEME-START[\s\S]*?THEME-END \*\//;

// Fallback: Match original format (for first-time migration)
// This matches from "/* Design System" or ":root {" through the closing of [data-theme="dark"]
const originalFormatRegex = /(\/\* Design System: Wabi-Sabi Edition \*\/\n)?:root \{[\s\S]*?\n\}\n\n\[data-theme="dark"\] \{[\s\S]*?\n\}/;

if (markerRegex.test(indexCss)) {
  // Replace existing generated block (has markers)
  indexCss = indexCss.replace(markerRegex, generatedCss);
} else if (originalFormatRegex.test(indexCss)) {
  // First-time migration from original format
  indexCss = indexCss.replace(originalFormatRegex, generatedCss);
} else {
  console.error('Could not find theme block in index.css');
  console.error('Expected either THEME-START/THEME-END markers or original :root format.');
  console.error('\nTo fix, ensure index.css has either:');
  console.error('  1. /* THEME-START */ ... /* THEME-END */ markers');
  console.error('  2. Original :root { ... } and [data-theme="dark"] { ... } blocks');
  process.exit(1);
}

// Write updated index.css
fs.writeFileSync(indexCssPath, indexCss);

console.log(`✓ Updated index.css with themes:`);
console.log(`  Light: ${lightTheme.displayName} (${lightTheme.name})`);
console.log(`  Dark:  ${darkTheme.displayName} (${darkTheme.name})`);
console.log(`\nTo preview changes: npm run dev`);
console.log(`To use different themes: npm run theme:generate -- --theme <light> <dark>`);
